function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlNumber(value: number): string {
  if (!Number.isFinite(value) || value <= 0) {
    throw new Error(`invalid_codex_numeric_config:${value}`);
  }
  return String(Math.floor(value));
}

export type CodexApplyPatchToolType = 'freeform';

function positiveInteger(value: number | undefined): number | undefined {
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) {
    return undefined;
  }
  return Math.floor(value);
}

export function resolveModelAutoCompactTokenLimit(args: {
  modelContextWindow?: number;
  modelMaxOutputTokens?: number;
  modelAutoCompactTokenLimit?: number;
}): number | undefined {
  const modelContextWindow = positiveInteger(args.modelContextWindow);
  const modelMaxOutputTokens = positiveInteger(args.modelMaxOutputTokens);
  const explicitCompactLimit = positiveInteger(args.modelAutoCompactTokenLimit);
  const derivedCompactLimit = modelContextWindow !== undefined && modelMaxOutputTokens !== undefined
    ? Math.max(1, modelContextWindow - modelMaxOutputTokens)
    : undefined;

  if (
    explicitCompactLimit !== undefined
    && (derivedCompactLimit === undefined || explicitCompactLimit === derivedCompactLimit)
  ) {
    return explicitCompactLimit;
  }

  return derivedCompactLimit ?? explicitCompactLimit;
}

function resolveEffectiveContextWindowPercent(args: {
  modelContextWindow: number;
  modelAutoCompactTokenLimit: number;
}): number {
  return Math.max(
    1,
    Math.round((args.modelAutoCompactTokenLimit / args.modelContextWindow) * 100),
  );
}

export function buildTaskCodexConfig(args: {
  model: string;
  endpointProxyBase: string;
  wireApi: 'responses';
  modelContextWindow?: number;
  modelMaxOutputTokens?: number;
  modelAutoCompactTokenLimit?: number;
  modelCatalogPath?: string;
  executionTicketHeaderEnvName?: string;
  codexDisableMultiAgent?: boolean;
}): string {
  const modelAutoCompactTokenLimit = resolveModelAutoCompactTokenLimit({
    modelContextWindow: args.modelContextWindow,
    modelMaxOutputTokens: args.modelMaxOutputTokens,
    modelAutoCompactTokenLimit: args.modelAutoCompactTokenLimit,
  });
  const lines: string[] = [
    '# Generated by agentsmith-runner for this task workspace.',
    '# Task-scoped Codex config loaded from ~/.codex/config.toml',
    `model = ${tomlString(args.model)}`,
    'model_provider = "proxy"',
    '',
    '# Reduce unsupported built-in tool usage for OpenAI-compatible third-party providers.',
    'web_search = "disabled"',
    '# Keep task output compact; reasoning is still available in tool/provider responses when needed.',
    'hide_agent_reasoning = true',
  ];
  if (args.codexDisableMultiAgent) {
    lines.push('features.multi_agent = false');
  }
  if (typeof args.modelContextWindow === 'number') {
    lines.push(`model_context_window = ${tomlNumber(args.modelContextWindow)}`);
  }
  if (typeof modelAutoCompactTokenLimit === 'number') {
    lines.push(`model_auto_compact_token_limit = ${tomlNumber(modelAutoCompactTokenLimit)}`);
  }
  if (args.modelCatalogPath && args.modelCatalogPath.trim().length > 0) {
    lines.push(`model_catalog_json = ${tomlString(args.modelCatalogPath)}`);
  }
  lines.push('');
  lines.push('[model_providers.proxy]');
  lines.push(`name = ${tomlString('Proxy')}`);
  lines.push(`base_url = ${tomlString(args.endpointProxyBase)}`);
  lines.push(`wire_api = ${tomlString(args.wireApi)}`);
  if (args.executionTicketHeaderEnvName && args.executionTicketHeaderEnvName.trim().length > 0) {
    lines.push(
      `env_http_headers = { ${tomlString('x-agentsmith-execution-ticket')} = ${tomlString(args.executionTicketHeaderEnvName)} }`,
    );
  }
  return `${lines.join('\n')}\n`;
}

export function buildCodexExecArgs(args: {
  model: string;
  prompt: string;
  cwd: string;
  endpointProxyBase: string;
  wireApi: 'responses';
  modelContextWindow?: number;
  modelMaxOutputTokens?: number;
  modelAutoCompactTokenLimit?: number;
  modelCatalogPath?: string;
  resumeSession?: boolean;
  codexDisableMultiAgent?: boolean;
}): string[] {
  const modelAutoCompactTokenLimit = resolveModelAutoCompactTokenLimit({
    modelContextWindow: args.modelContextWindow,
    modelMaxOutputTokens: args.modelMaxOutputTokens,
    modelAutoCompactTokenLimit: args.modelAutoCompactTokenLimit,
  });
  const cliArgs = [
    'exec',
    '--skip-git-repo-check',
    '--json',
    '--model',
    args.model,
    '-c',
    'model_provider="proxy"',
    '-c',
    'model_providers.proxy.name="Proxy"',
    '-c',
    `model_providers.proxy.base_url=${JSON.stringify(args.endpointProxyBase)}`,
    '-c',
    `model_providers.proxy.wire_api=${JSON.stringify(args.wireApi)}`,
    '-c',
    'project_root_markers=[]',
    '-c',
    `projects.${JSON.stringify(args.cwd)}.trust_level="trusted"`,
    '-c',
    'web_search="disabled"',
    '-c',
    'hide_agent_reasoning=true',
  ];
  if (args.codexDisableMultiAgent) {
    cliArgs.push(
      '-c',
      'features.multi_agent=false',
    );
  }
  if (typeof args.modelContextWindow === 'number') {
    cliArgs.push(
      '-c',
      `model_context_window=${tomlNumber(args.modelContextWindow)}`,
    );
  }
  if (typeof modelAutoCompactTokenLimit === 'number') {
    cliArgs.push(
      '-c',
      `model_auto_compact_token_limit=${tomlNumber(modelAutoCompactTokenLimit)}`,
    );
  }
  if (args.modelCatalogPath && args.modelCatalogPath.trim().length > 0) {
    cliArgs.push(
      '-c',
      `model_catalog_json=${JSON.stringify(args.modelCatalogPath)}`,
    );
  }
  cliArgs.splice(1, 0, '--dangerously-bypass-approvals-and-sandbox');
  if (args.resumeSession) {
    cliArgs.splice(1, 0, 'resume', '--last');
  }
  cliArgs.push(args.prompt);
  return cliArgs;
}

export function buildTaskCodexModelCatalog(args: {
  model: string;
  modelContextWindow: number;
  modelMaxOutputTokens?: number;
  modelAutoCompactTokenLimit?: number;
  applyPatchToolType: CodexApplyPatchToolType;
  inputModalities?: string[];
  supportsSearchTool?: boolean;
  supportsParallelToolCalls?: boolean;
}): string {
  const modelContextWindow = positiveInteger(args.modelContextWindow);
  if (modelContextWindow === undefined) {
    throw new Error(`invalid_codex_model_context_window:${args.modelContextWindow}`);
  }
  const modelAutoCompactTokenLimit = resolveModelAutoCompactTokenLimit({
    modelContextWindow,
    modelMaxOutputTokens: args.modelMaxOutputTokens,
    modelAutoCompactTokenLimit: args.modelAutoCompactTokenLimit,
  }) ?? Math.max(1, Math.floor(modelContextWindow * 0.9));
  const effectiveContextWindowPercent = resolveEffectiveContextWindowPercent({
    modelContextWindow,
    modelAutoCompactTokenLimit,
  });
  const inputModalities = Array.isArray(args.inputModalities) && args.inputModalities.length > 0
    ? [...new Set(args.inputModalities.map((item) => item.trim()).filter((item) => item.length > 0))]
    : ['text'];
  const catalog = {
    models: [
      {
        slug: args.model,
        display_name: args.model,
        description: 'AgentSmith endpoint-backed Codex model.',
        default_reasoning_level: 'medium',
        supported_reasoning_levels: [
          { effort: 'low', description: 'Fast responses with lighter reasoning' },
          { effort: 'medium', description: 'Balances speed and reasoning depth for everyday tasks' },
          { effort: 'high', description: 'Greater reasoning depth for complex problems' },
          { effort: 'xhigh', description: 'Extra high reasoning depth for complex problems' },
        ],
        shell_type: 'shell_command',
        visibility: 'list',
        supported_in_api: true,
        priority: 0,
        availability_nux: null,
        upgrade: null,
        base_instructions:
          'You are Codex, a coding agent based on GPT-5. You and the user share the same workspace and collaborate to achieve the user\'s goals.',
        model_messages: null,
        supports_reasoning_summaries: false,
        default_reasoning_summary: 'auto',
        support_verbosity: false,
        default_verbosity: null,
        apply_patch_tool_type: args.applyPatchToolType,
        web_search_tool_type: 'text',
        truncation_policy: { mode: 'bytes', limit: 10000 },
        supports_parallel_tool_calls: args.supportsParallelToolCalls ?? false,
        supports_image_detail_original: false,
        context_window: modelContextWindow,
        auto_compact_token_limit: modelAutoCompactTokenLimit,
        effective_context_window_percent: effectiveContextWindowPercent,
        experimental_supported_tools: [],
        input_modalities: inputModalities,
        supports_search_tool: args.supportsSearchTool ?? false,
      },
    ],
  };
  return `${JSON.stringify(catalog, null, 2)}\n`;
}
