import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { TaskWorkspacePaths } from './task-workspace.js';

export type AgentTaskInput = {
  kind?: 'library_object' | 'artifact' | 'url';
  library_id?: string;
  key?: string;
  task_id?: string;
  artifact_id?: string;
  task_relative_path?: string;
  url?: string;
  imported_library_id?: string;
  imported_key?: string;
  filename?: string;
  file_type?: string;
  file_size?: number;
};

export type TaskAssetExecutionContext = {
  task_id?: string;
  run_id?: string;
  workspace_binding_mode?: 'file_library' | 'pre_mounted';
};

type TaskAssetDebugLog = (message: string, extra?: Record<string, unknown>) => void;

export function buildTaskHeadlessPreamble(args: {
  artifactsDir: string;
}): string {
  return [
    'Agent task execution policy (headless execution):',
    '- This environment is headless. Do not open GUI windows or interactive viewers.',
    '- Do not call blocking UI display operations such as matplotlib plt.show().',
    `- Save charts/images/files to the artifacts directory: ${args.artifactsDir}`,
    '- Put final textual conclusions in your response; put generated files in artifacts.',
    '',
    'Use files already present in the workspace to complete the user request and mention generated artifact filenames in your final response.',
    '',
  ].join('\n');
}

function buildTaskAgentsMd(): string {
  return [
    '# AGENTS.md (generated by agentsmith-runner)',
    '',
    '## Agent Task Execution Rules (Mandatory)',
    '',
    '1. This task runs in a headless environment. Do not open GUI windows or interactive viewers.',
    '2. Do not call blocking display APIs (for example: matplotlib.pyplot.show()).',
    '3. Save generated files/charts/images into `./.artifacts/`; `ARTIFACTS_PATH` points to the same directory.',
    '4. Put final conclusions in the response message, and mention generated artifact filenames.',
    '5. `HOME` is the persistent task HOME; `TASK_HOME` points to the same directory.',
    '6. The current working directory is `$HOME/workspace`, also exposed as `WORKSPACE_PATH`.',
    '7. Keep dynamic config, caches, installs, and toolchains under `HOME`; keep short-lived tickets, secrets, and connection credentials request-scoped.',
    '8. Builtin skills are installed under `~/.agents/skills`. Do not rely on `/etc/codex` for mutable runtime state.',
    '9. Builtin skills may declare opaque dependency names. They only consume request-scoped projections supplied by AgentSmith; do not pass credentials as CLI parameters.',
    '10. Context policy, write policy, and credential resolution are defined by AgentSmith and the formal runner contract artifacts, not by local runner docs.',
    '11. If a required projection is unavailable, fail fast instead of searching workspace files for hidden config.',
    '12. If you need Python / Node / Rust tools or libraries, install them in user mode only so they stay under `HOME`.',
    '13. Generated deliverables belong in `./.artifacts/` (also exposed as `ARTIFACTS_PATH`); `$HOME/.artifacts`, `$HOME/.mbos`, `$HOME/.codex`, `$HOME/.agents`, and `$HOME/.local` are not collected as artifacts.',
    '',
    '## Output Convention',
    '',
    '- Text summary -> final response message',
    '- Files/images -> `./.artifacts/` (system will collect these as task artifacts)',
    '- AgentSmith runner state -> `$HOME/.mbos/`',
    '- Codex runtime state -> `$HOME/.codex/`',
    '- Builtin + user skills -> `$HOME/.agents/skills/`',
    '- Agent-facing projected dependencies -> use capability-aware builtin skills first; use `mbos-context` only to inspect request-scoped projections',
    '',
    '## User-Mode Install Rules',
    '',
    '- Python: use user installs rooted at `~/.local` (for example `python3 -m pip install --user ...`).',
    '- Node: use a user prefix rooted at `~/.local` and avoid global/system installs.',
    '- Rust: use `CARGO_HOME=~/.cargo` and `RUSTUP_HOME=~/.rustup` inside `HOME`.',
    '- Prefer commands that keep binaries under `~/.local/bin` or `~/.cargo/bin`.',
    '',
  ].join('\n');
}

function buildRunnerRuntimeMd(): string {
  return [
    '# RUNNER_RUNTIME.md (generated by agentsmith-runner)',
    '',
    '## Runtime Contract',
    '',
    '- `HOME` is the persistent task HOME; `TASK_HOME` points to the same directory.',
    '- `cwd` is `$HOME/workspace`; `WORKSPACE_PATH` points to the same directory.',
    '- Task artifacts belong in `$HOME/workspace/.artifacts`; `ARTIFACTS_PATH` points to the same directory.',
    '- Dynamic configuration, caches, package installs, and toolchains may stay under the persistent task HOME; short-lived tickets, secrets, and connection credentials must stay request-scoped.',
    '- Builtin skills are installed under `~/.agents/skills`.',
    '- AgentSmith may provide request-scoped dependency projections for builtin skills. The runner consumes those projections by opaque dependency name only.',
    '- Context policy, write policy, and credential resolution are defined by AgentSmith and the formal runner contract artifacts, not by this runner repository.',
    '- Builtin skills can ship machine-readable descriptors listing dependency names and expected fields, but they must not infer product policy from those descriptors.',
    '- Codex runtime state is stored under `$HOME/.codex`.',
    '- Task output files belong in `$HOME/workspace/.artifacts`.',
    '- `$HOME/.artifacts`, `$HOME/.mbos`, `$HOME/.codex`, `$HOME/.agents`, and `$HOME/.local` are runtime/state directories, not task artifact directories.',
    '',
    '## User-Mode Install Rules',
    '',
    '- Python: install with user mode rooted at `~/.local`.',
    '- Node: install with a user prefix rooted at `~/.local`.',
    '- Rust: keep `CARGO_HOME=~/.cargo` and `RUSTUP_HOME=~/.rustup`.',
    '- Never write mutable runtime state to `/etc`, `/usr/local`, `/opt`, or shared system directories.',
    '',
  ].join('\n');
}

export async function prepareTaskWorkspaceAssets(args: {
  cwd: string;
  paths: TaskWorkspacePaths;
  executionContext: TaskAssetExecutionContext;
  taskInputs: AgentTaskInput[];
  debugLog?: TaskAssetDebugLog;
}): Promise<{
  artifactsDir: string;
}> {
  const { cwd, paths, executionContext, taskInputs, debugLog } = args;
  const artifactsDir = paths.artifactsDir;
  await withFsOpTimeout(
    'task_assets_mkdir_mbos',
    mkdir(paths.mbosDir, { recursive: true }),
    debugLog,
    { cwd, target: paths.mbosDir },
  );
  await withFsOpTimeout(
    'task_assets_mkdir_artifacts',
    mkdir(artifactsDir, { recursive: true }),
    debugLog,
    { cwd, target: artifactsDir },
  );
  debugLog?.('task_assets_inputs_ignored', {
    cwd,
    task_inputs_count: taskInputs.length,
  });
  const agentsPath = join(cwd, 'AGENTS.md');
  if (!existsSync(agentsPath)) {
    await withFsOpTimeout(
      'task_assets_write_agents_md',
      writeFile(agentsPath, buildTaskAgentsMd(), 'utf-8'),
      debugLog,
      { cwd, target: agentsPath, workspace_binding_mode: executionContext.workspace_binding_mode ?? null },
    );
  }
  const runtimeContractPath = join(paths.mbosDir, 'RUNNER_RUNTIME.md');
  await withFsOpTimeout(
    'task_assets_write_runner_runtime_md',
    writeFile(runtimeContractPath, buildRunnerRuntimeMd(), 'utf-8'),
    debugLog,
    { cwd, target: runtimeContractPath },
  );
  return { artifactsDir };
}

async function withFsOpTimeout<T>(
  name: string,
  promise: Promise<T>,
  debugLog?: TaskAssetDebugLog,
  extra?: Record<string, unknown>,
): Promise<T> {
  const timeoutMs = Number.parseInt(process.env.MBOS_AGENT_TASK_ASSET_IO_TIMEOUT_MS ?? '30000', 10);
  const startedAt = Date.now();
  debugLog?.(`${name}_start`, extra);
  let timer: NodeJS.Timeout | undefined;
  try {
    const result = await Promise.race<T>([
      promise,
      new Promise<T>((_resolve, reject) => {
        timer = setTimeout(() => {
          reject(new Error(`${name}_timeout_after_${String(timeoutMs)}ms`));
        }, timeoutMs);
      }),
    ]);
    debugLog?.(`${name}_done`, {
      ...extra,
      duration_ms: Date.now() - startedAt,
    });
    return result;
  } finally {
    if (timer) clearTimeout(timer);
  }
}
